# Markdownlint configuration
# https://github.com/DavidAnson/markdownlint

# MD013: Line length
MD013:
  line_length: 120
  code_blocks: false
  tables: false

# MD033: Inline HTML
MD033:
  allowed_elements:
    - br
    - details
    - summary
    - img

# MD041: First line in file should be a top level heading
MD041: false

# MD024: Multiple headings with the same content
MD024:
  siblings_only: true

# MD046: Code block style
MD046:
  style: fenced

# MD060: Table column style
MD060:
  style: aligned
