# Prettier configuration for markdown formatting
# https://prettier.io/docs/en/options.html

printWidth: 120
proseWrap: preserve
tabWidth: 2
useTabs: false

# Markdown-specific
overrides:
  - files: "*.md"
    options:
      proseWrap: preserve
      printWidth: 120
